/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qbyteconsulting_HyperOrderIF */

#ifndef _Included_com_qbyteconsulting_HyperOrderIF
#define _Included_com_qbyteconsulting_HyperOrderIF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    initialiseDLL
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_qbyteconsulting_HyperOrderIF_initialiseDLL
  (JNIEnv *, jclass);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    isHostRunning
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qbyteconsulting_HyperOrderIF_isHostRunning
  (JNIEnv *, jclass);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    isHostConnected
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qbyteconsulting_HyperOrderIF_isHostConnected
  (JNIEnv *, jclass);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    getAccountCashBalance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_qbyteconsulting_HyperOrderIF_getAccountCashBalance
  (JNIEnv *, jclass);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    getAccountUpdateTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qbyteconsulting_HyperOrderIF_getAccountUpdateTime
  (JNIEnv *, jclass);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    getAccountItem
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_qbyteconsulting_HyperOrderIF_getAccountItem
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    getFirstOpenOrder
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_getFirstOpenOrder
  (JNIEnv *, jclass);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    getNextOpenOrder
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_getNextOpenOrder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    buyMarket
 * Signature: ([C[C[C[CF[C[CI)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_buyMarket
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring, jstring, jint);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    sellMarket
 * Signature: ([C[C[C[CF[C[CI)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_sellMarket
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring, jstring, jint);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    buyLimit
 * Signature: ([C[C[C[CF[C[CIF)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_buyLimit
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring, jstring, jint, jfloat);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    sellLimit
 * Signature: ([C[C[C[CF[C[CIF)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_sellLimit
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring, jstring, jint, jfloat);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    buyStop
 * Signature: ([C[C[C[CF[C[CIF)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_buyStop
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring, jstring, jint, jfloat);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    sellStop
 * Signature: ([C[C[C[CF[C[CIF)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_sellStop
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring, jstring, jint, jfloat);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    buyStopLimit
 * Signature: ([C[C[C[CF[C[CIFF)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_buyStopLimit
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring, jstring, jint, jfloat, jfloat);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    sellStopLimit
 * Signature: ([C[C[C[CF[C[CIFF)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_sellStopLimit
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring, jstring, jint, jfloat, jfloat);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    BuyTrailStop
 * Signature: ([C[C[C[CF[C[CIF)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_BuyTrailStop
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring, jstring, jint, jfloat);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    sellTrailStop
 * Signature: ([C[C[C[CF[C[CIF)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_sellTrailStop
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring, jstring, jint, jfloat);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    cancelOrder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qbyteconsulting_HyperOrderIF_cancelOrder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    cancelAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qbyteconsulting_HyperOrderIF_cancelAll
  (JNIEnv *, jclass);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    cancelAllFor
 * Signature: ([C[C[C[CF[C[C)V
 */
JNIEXPORT void JNICALL Java_com_qbyteconsulting_HyperOrderIF_cancelAllFor
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring, jstring);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    getMarketPosition
 * Signature: ([C[C[C[CF[C)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_getMarketPosition
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    closePositionFor
 * Signature: ([C[C[C[CF[C[C)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_closePositionFor
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jfloat, jstring, jstring);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    startOCAGroup
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_qbyteconsulting_HyperOrderIF_startOCAGroup
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    stopOCAGroup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qbyteconsulting_HyperOrderIF_stopOCAGroup
  (JNIEnv *, jclass);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    setTIF
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_qbyteconsulting_HyperOrderIF_setTIF
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    getOrderStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qbyteconsulting_HyperOrderIF_getOrderStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    getOrderPrice
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_qbyteconsulting_HyperOrderIF_getOrderPrice
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    getOrderFilled
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_getOrderFilled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    getOrderRemaining
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_getOrderRemaining
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    writeIntValue
 * Signature: ([CI)V
 */
JNIEXPORT void JNICALL Java_com_qbyteconsulting_HyperOrderIF_writeIntValue
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    readIntValue
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_com_qbyteconsulting_HyperOrderIF_readIntValue
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    writeLongValue
 * Signature: ([CJ)V
 */
JNIEXPORT void JNICALL Java_com_qbyteconsulting_HyperOrderIF_writeLongValue
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    readLongValue
 * Signature: ([C)J
 */
JNIEXPORT jlong JNICALL Java_com_qbyteconsulting_HyperOrderIF_readLongValue
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    writeFloatValue
 * Signature: ([CF)V
 */
JNIEXPORT void JNICALL Java_com_qbyteconsulting_HyperOrderIF_writeFloatValue
  (JNIEnv *, jclass, jstring, jfloat);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    readFloatValue
 * Signature: ([C)F
 */
JNIEXPORT jfloat JNICALL Java_com_qbyteconsulting_HyperOrderIF_readFloatValue
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    writeStringValue
 * Signature: ([C[C)V
 */
JNIEXPORT void JNICALL Java_com_qbyteconsulting_HyperOrderIF_writeStringValue
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    readStringValue
 * Signature: ([C)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qbyteconsulting_HyperOrderIF_readStringValue
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    soundAlert
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_qbyteconsulting_HyperOrderIF_soundAlert
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qbyteconsulting_HyperOrderIF
 * Method:    popupAlert
 * Signature: ([C[C)V
 */
JNIEXPORT void JNICALL Java_com_qbyteconsulting_HyperOrderIF_popupAlert
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
