#ifndef _Included_HyperOrderIFPeer
#define _Included_HyperOrderIFPeer

/*
 *  Interface file for class HyperOrderIFPeer
 *  
 *  Initially generated by: JPeerGen v0.9.0 - http://jpeergen.sf.net/
 */
#include <jni.h>

class HyperOrderIFPeer {
public:
    /*
     *  *** Do not remove the following include.  It contains
     *      the peer binding methods that the JNI stub will call
     *      on this peer class.
     */
    #include "HyperOrderIFBindings.h"
};
#endif
